### ISSUE TITLE
In the instructions it mentions you need a password to unzip the bundle.

### ISSUE THREAD

**Issue by kurtroberts** [matterport/showcase-sdk-examples#18]
Where would that password come from?

**Comment by chris-aeviator** [comment]
@matterport seriously? Facing the same "issue"

**Comment by codingtub** [comment]
You can request the .zip password by contacting Matterport via email [developers@matterport.com](mailto:developers@matterport.com). We received the password within about a day.

**Comment by yusuketakagi30** [comment]
Where would that password come from?

**Comment by gbruce** [comment]
Hi @yusuketakagi30, the sdk bundle no longer requires a password. You will need a matterport account to get an sdk key, see https://support.matterport.com/hc/en-us/articles/360057506813-Matterport-Developer-Tools-Pricing-and-Availability about sandbox mode.

**Comment by cheahph** [comment]
the instruction is not clear which I believe is not updated. First, Where to get the password for the bundle file? next ,if password is not needed, what are the steps to get it working

**Comment by chris-aeviator** [comment]
> You can request the .zip password by contacting Matterport via email [developers@matterport.com](mailto:developers@matterport.com). We received the password within about a day.

@cheahph it's pretty clear no?

**Comment by cheahph** [comment]
thanks @chris-aeviator , but @gbruce mentioned the password is not required, so a bit confusing..

**Comment by chris-aeviator** [comment]
@cheahph since this is git which allows to "travel back in time" it will always be required if working with an old release of the file =)

**Comment by gbruce** [comment]
I think I see the an error in the documentation, the curl command shows version 3.1.8.2-12-g86e1cdce6. 
Sorry for that confusion.

To get the latest bundle, you can run
`yarn fetch-bundle && yarn expand-bundle` which should download version 3.1.16.9-17-gacf9fb85e
automatically. You shouldn't have to manually run the curl command.

**Comment by gbruce** [comment]
You can always see the latest version here: https://matterport.github.io/showcase-sdk/sdkbundle_home.html

**Comment by chris-aeviator** [comment]
@gbruce can't you just put that password into the readme for everyone that's still facing this?

**Comment by gbruce** [comment]
Just updated the README with the password for the older beta builds.

**Comment by cheahph** [comment]
thanks! Just wonder has anyone make it works? I tried the whole day but I cannot make it works.....:(
here is the error.
![matterportError](https://user-images.githubusercontent.com/15076353/104677231-063c8200-5724-11eb-9a0e-d5dda5dd397c.png)

**Comment by lucazamm** [comment]
@cheahph I hope you need a valid Matterport Application Key. To obaint it you need to have a Matterport account.

best
Luca

**Comment by dmtaub** [comment]
Closing this old issue. For future help, please visit https://matterport.com/platform/developers to contact the SDK support team.
