### ISSUE TITLE
... 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by manu-adina** [matterport/showcase-sdk-examples#20]
Hi,

When I follow the instructions, I get the following error.

Access to XMLHttpRequest at 'https://my.matterport.com/api/v1/user/' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

I can't seem to get examples working, I'm using Chrome, Ubuntu 18.04 (on VMWare).

**Comment by kr45122** [comment]
@manu-adina - Any chance you can help us understand how you closed this error?  We are seeing the same issue.

**Comment by manu-remsense** [comment]
> @manu-adina - Any chance you can help us understand how you closed this error? We are seeing the same issue.

CORS errors pop up several times, however you have to look at the last error. It may say key/error mismatch. That error basically states that the SDK key for the space is wrong. You have to set the SDK key in the files first. The file is in the /packages/src/index.ts open the file. Scroll to the bottom, it will have a key there. Replace the SDK key with your key.

Launch whatever app you're trying to launch, for this example I'll use inspector, run 'yarn inspector' and go to url localhost:8000/?m={your model id here}. Important: the model has to be set to "Anyone can view" in the matterport portal.

**Comment by manu-adina** [comment]
> @manu-adina - Any chance you can help us understand how you closed this error? We are seeing the same issue.

@kr45122 
This is how I fixed it on my end

CORS errors pop up several times, however you have to look at the last error. It may say key/error mismatch. That error basically states that the SDK key for the space is wrong. You have to set the SDK key in the files first. The file is in the /packages/src/index.ts open the file. Scroll to the bottom, it will have a key there. Replace the SDK key with your key.

Launch whatever app you're trying to launch, for this example I'll use inspector, run 'yarn inspector' and go to url localhost:8000/?m={your model id here}. Important: the model has to be set to "Anyone can view" in the matterport portal.
