### ISSUE TITLE
Where to insert Application Key, SDK key and ModelId

### ISSUE THREAD

**Issue by cheahph** [matterport/showcase-sdk-examples#23]
I was going through the Readme file for instruction on where to insert the Application Key, SDK key and ModelId, but could not find it..By referring to [https://matterport.github.io/showcase-sdk/sdkbundle_tutorials_setup.html], the files should be index.html and index.ts, but it looks different for this case..

**Comment by lucazamm** [comment]
Hi,
you have to set both of them into the query string parameter. For example if you ran vs-app or inspector this is the url example: 

http://localhost:8000?applicationKey=<applicationKey>&m=<modelId>

Best
Luca

**Comment by dmtaub** [comment]
Closing this old issue. For future help, please visit https://matterport.com/platform/developers for documentation or to contact the SDK support team.
