### ISSUE TITLE
Existing SDK key does not work with new API Version

### ISSUE THREAD

**Issue by klipitkas** [matterport/showcase-sdk-examples#25]
Hello guys, I tried to update to the latest version of the SDK (I was using some 2.x version before).

I am using the bundle **3.1.33.13-11-gbd71a02c0** and have unzipped it locally. I am using the code that can be seen below:

**index.html**
```html
<iframe
  width="100%"
  height="100%"
  src="/bundle/showcase.html?applicationKey=[SDK_KEY]&m=[MODEL_SID]"
  frameborder="0"
  allowfullscreen
  allow="xr-spatial-tracking"
  id="showcase"
></iframe>
```
The javascript in place is the following:

**index.html**
```js
var showcase = document.getElementById('showcase');

showcase.addEventListener('load', async function () {
  let sdk;
  try {
    sdk = await showcase.contentWindow.MP_SDK.connect(
      showcase,
      '[SDK_KEY]',
      '3.8'
    );
  } catch (e) {
    console.error('ERRRRRRRRRRRRRRRRRRRRRRRRRRROR', e);
    return;
  }

  console.log('Hello Bundle SDK', sdk);
});
```

This is currently running on `http://localhost:8080`. The file and directory structure is the following:
```
.
├── bundle
│   ├── css
│   ├── cursors
│   ├── fonts
│   ├── images
│   ├── js
│   ├── locale
│   ├── mattertag
│   ├── node_modules
│   ├── package.json
│   ├── package-lock.json
│   ├── sdk-client.js
│   ├── showcase.html
│   ├── terms
│   └── version.txt
├── index.html
└── README.md
```

My SDK Key is working on Sandbox mode at the moment and domains:
```
Domains
http & https
localhost:8080
```

![Screenshot from 2021-02-17 16-03-45](https://user-images.githubusercontent.com/3259834/108216408-1c7e9900-713b-11eb-851a-1e786c73eb68.png)

**Comment by klipitkas** [comment]
Using an older version of your API **3.1.28.5-4-g911543b43** seems to work.

**Comment by gbruce** [comment]
try re-installing the bundle, the file packages/bundle/showcase.html should have apiHost config parameter.
```
  var detailObject = {
    config: {"apiHost":"https://my.matterport.com","pointerPreventDefault":false}
  };
```
A version we released earlier in the day yesterday omitted that parameter.

**Comment by klipitkas** [comment]
> config: {"apiHost":"https://my.matterport.com","pointerPreventDefault":false}

Thank re-installing the bundle made it work.
