### ISSUE TITLE
"yarn bootstrap" throwing --> Couldn't find package "@mp/bundle-sdk@^1.0.0" required by "vs-app@1.0.0"

### ISSUE THREAD

**Issue by a-dodhy** [matterport/showcase-sdk-examples#37]
I have been trying to setup the showcase-sdk-examples but keep getting the `Error: Couldn't find package "@mp/bundle-sdk@^1.0.0" required by "vs-app@1.0.0" on the "npm" registry.` error message when I try to run the `yarn bootstrap` command.

### Steps to reproduce

1. Cloned the latest repository of the project `git clone https://github.com/matterport/showcase-sdk-examples.git`
2. Successfully ran `yarn install` inside the /showcase-sdk-examples repo
3. Updated the `bundle_version` to `3.1.41.5-19-g5133fdd3e` in the `package.json` so that the latest bundle version downloaded and unzipped in the "showcase-sdk-examples\packages\bundle" directory.
4. Ran `yarn bootstrap`, which throws the following error
![image](https://user-images.githubusercontent.com/40954122/121386014-ed8a6e00-c949-11eb-8ee6-7c72310186bc.png)

### Setup
Yarn version: 1.19.2
bundle version: 3.1.41.5-19-g5133fdd3e
Node version: 14.15.4
OS: Windows10
IDE: Webstorm

### Note
I tried search the @mp/bundle-sdk on the npm registry (https://www.npmjs.com/search?q=bundle-sdk) and I do not see the package there either.

Could you please help me out with this?
Thanks

**Comment by sandersdevelopments** [comment]
I'd like to have this package too, to get the types and fix the intellisense... unfortunately their documentation is quite outdated and a lot of things are hidden. If the devs would provide more information --> more developers could serve their clients needs --> matterport grows

**Comment by Korea-code** [comment]
I solved the problem. All you need to do is adding package.json in the packages/bundle . 
The content is
```
{
  "name": "@mp/bundle-sdk",
  "version": "1.0.0",
  "main": "js/showcase.js"
}
```

**Comment by dmtaub** [comment]
Closing this old issue. For future help, please visit https://matterport.com/platform/developers for documentation or to contact the SDK support team.
