### ISSUE TITLE
yarn embed-examples api/v1/user 400 

### ISSUE THREAD

**Issue by leesgithub2019** [matterport/showcase-sdk-examples#41]
url: http://localhost:8000/sensor-point-areas/index.html

![image](https://user-images.githubusercontent.com/48384080/129899241-332244da-479f-4bf7-8310-a0809833574c.png)

I haven't changed anything.

**Comment by gbruce** [comment]
You will need a matterport sdk key to run the examples (See https://support.matterport.com/hc/en-us/articles/360057506813-Matterport-Developer-Tools-Pricing-and-Availability). You will also need to replace the key in this line with your own
https://github.com/matterport/showcase-sdk-examples/blob/master/packages/common/src/index.ts#L75

See https://support.matterport.com/hc/en-us/articles/360057506813-Matterport-Developer-Tools-Pricing-and-Availability

**Comment by leesgithub2019** [comment]
> You will need a matterport sdk key to run the examples (See https://support.matterport.com/hc/en-us/articles/360057506813-Matterport-Developer-Tools-Pricing-and-Availability). You will also need to replace the key in this line with your own
> https://github.com/matterport/showcase-sdk-examples/blob/master/packages/common/src/index.ts#L75
> 
> See https://support.matterport.com/hc/en-us/articles/360057506813-Matterport-Developer-Tools-Pricing-and-Availability

Thanks！

I'll try it now.

**Comment by leesgithub2019** [comment]
I get matterport sdk key
![image](https://user-images.githubusercontent.com/48384080/130026715-f9b7ff91-9b80-4772-b645-5ddb7172f121.png)

and replace the key 
![image](https://user-images.githubusercontent.com/48384080/130026958-78797a15-7e2d-4f8e-9eef-44a20af28ac1.png)

but it still not work.
![image](https://user-images.githubusercontent.com/48384080/130027129-505b46b3-be0f-45bd-8299-aa8ca4afc1c0.png)

please help me.

**Comment by leesgithub2019** [comment]
it works!

thanks!
