### ISSUE TITLE
Is it hosted on a central server? How to configure on our own server?

### ISSUE THREAD

**Issue by ishan501** [matterport/showcase-sdk-examples#43]
Hi,
I can see the tours on the demo page that I created on my website!
https://matterport.github.io/showcase-sdk/sdk_remote_control.html

So, it looks like a central server is used. How can I set this up on my server?
Thanks in advance!

**Comment by radarxtech** [comment]
THIS.... 1000% times...  Matterport... webhooks and local dev is only a small part of this potential...

**Comment by dmtaub** [comment]
Hello, this demo is just an example, for which we use our own SDK key of the [Photon engine.](https://www.photonengine.com) 

If you want your own separate channel, you can register with them and insert your own SDK key here:
https://github.com/matterport/showcase-sdk-examples/blob/master/packages/rc-app/src/PhotonClient.ts#L12

If you have other questions, please visit https://matterport.com/platform/developers for documentation or to contact the SDK support team.
