### ISSUE TITLE
'key' is declared but its value is never read.

### ISSUE THREAD

**Issue by hoangnguyen1222** [matterport/showcase-sdk-examples#51]
![image](https://user-images.githubusercontent.com/75771772/139682944-ce3bb703-19c3-47b9-a26a-c2bb86bafbc5.png)

**Comment by dmtaub** [comment]
I can't tell the issue from this amount of information. If this is still happening, please visit https://matterport.com/platform/developers for complete documentation or to contact the SDK support team
