### ISSUE TITLE
Calling unzip of bundle

### ISSUE THREAD

**Issue by romanallosense** [matterport/showcase-sdk-examples#6]
Using MacBook Pro OSX Mojave 10.14.6.

I get the following response when calling:
```
$ unzip -o bundle.zip -d ./packages/bundle
Archive:  bundle.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of bundle.zip or
        bundle.zip.zip, and cannot find bundle.zip.ZIP, period.
```
I am not able to enter a password and it seems like the file is corrupted.

**Comment by gbruce** [comment]
Did you run `yarn install-bundle`?

**Comment by romanallosense** [comment]
Yes, I did.  That part worked fine after plugging in the SDK code.

**Comment by romanallosense** [comment]
I also tried reinstalling unzip but to no avail:
`brew reinstall unzip`

**Comment by gbruce** [comment]
what size is the bundle.zip file? Could you post it here?

**Comment by romanallosense** [comment]
```
$ stat bundle.zip 
16777221 8650460885 -rw-r--r-- 1 romansandoval staff 0 243 "Jun 17 00:47:53 2020" "Jun 16 23:34:17 2020" "Jun 16 23:34:17 2020" "Jun 16 22:53:44 2020" 4096 8 0 bundle.zip
```
<img width="262" alt="Screen Shot 2020-06-17 at 11 49 52 AM" src="https://user-images.githubusercontent.com/54388910/84926251-b6fc7900-b090-11ea-8558-c9bfc8e00ef7.png">

**Comment by gbruce** [comment]
The size of the file seems off. It should be ~2.4mb. Could you try downloading the bundle again?

**Comment by romanallosense** [comment]
Hi,
It seems like the file size is still 243 bytes:
`$ curl https://static.matterport.com/misc/bundle/showcase/$npm_package_config_bundle_version/showcase-bundle.zip -o bundle.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   243    0   243    0     0    674      0 --:--:-- --:--:-- --:--:--   675`

Could this be an issue with resolving the $npm_package_config_bundle_version?

**Comment by romanallosense** [comment]
I see the discrepancy here.  The README in this repo references:
`$ curl https://static.matterport.com/misc/bundle/showcase/$npm_package_config_bundle_version/showcase-bundle.zip -o bundle.zip`

Whereas the tutorial (https://matterport.github.io/showcase-sdk/sdkbundle_tutorials_setup.html) references:
```
> curl https://static.matterport.com/misc/bundle/showcase/3.0.35.31-25-g9563c7a6c/showcase-bundle.zip -o bundle.zip
> unzip bundle.zip -d ./bundle
```

Similarly, the SDK Section has a different approach:

**Comment by gbruce** [comment]
Yes, thats it. The readme has the wrong string.  Sorry for the confusion. I will change the readme. The shell output was meant to show the output of running `yarn install-bundle`. Thanks for pointing this out.

**Comment by romanallosense** [comment]
Thanks for confirming this!
