### ISSUE TITLE
DOM Exception: Data clone error on creating Scene objects

### ISSUE THREAD

**Issue by Huma2k10** [matterport/showcase-sdk-examples#64]
I am using matterport with react typescript. It gives a Data clone error when I try to create an Object. I am using the "3.1.64.4-0-gea16b080c2" version of matterport SDK. I have also tried loading the SDK via CDN but the Scene component seems to be missing from that one. 
 Error I am facing is "Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Window': ()=>nt(OBJLoader2Component) could not be cloned."

**Comment by dmtaub** [comment]
Hello, the version number you posted is for the "Bundle SDK." There is no Scene namespace currently available in the Embed SDK (what you load from CDN).

For more information on the difference between the SDKs, please visit https://matterport.com/platform/developers - you can also contact the SDK support team from there if you still have questions.

We expect to be posting an update to the documentation in the coming weeks, which will hopefully make this distinction a little more clear.
