### ISSUE TITLE
question:What should I do to make vs-app work properly

### ISSUE THREAD

**Issue by yoshiki-hosokawa** [matterport/showcase-sdk-examples#83]
When I run the following command, I get the following error
I would like to know the solution.

`$ yarn vs-app`

vs-app: <i> [webpack-dev-server] Content not from webpack is served from '/home/matterport-test/showcase-sdk-examples/packages/vs-app/public' directory

**Comment by AustinDoss** [comment]
That log is expected from webpack
https://webpack.js.org/configuration/dev-server/

I will be closing this issue, but please reach out to developer@matterport.com if you have further questions.
